#!/bin/bash

# JankyBorders configuration
# Dynamic colours set by ~/.config/sketchybar/plugins/borders.sh
# - Floating: white
# - Tiled: pastel orange

borders \
    style=round \
    width=12.0 \
    hidpi=on \
    active_color=0xffFAFAFA \
    inactive_color=0x1Affffff
