#!/bin/bash

# JankyBorders configuration
# Pairs with AeroSpace tiling window manager

borders \
    style=round \
    width=6.0 \
    hidpi=on \
    active_color=0xffFAFAFA \
    inactive_color=0x00000000
