# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load antidote
source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh

# Load plugins from the list
antidote load

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
eval "$(zoxide init zsh)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/n0id/.lmstudio/bin"
# End of LM Studio CLI section

# Load custom aliases
[ -f ~/.zsh_aliases ] && source ~/.zsh_aliases

# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/n0id/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions

# Pocket 3 ingest shortcut
alias p3="python3 /Users/n0id/Dev/Scripts/pocket3ingest.py"