# Load antidote
source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh

# Load plugins from the list
antidote load

# Starship prompt
eval "$(starship init zsh)"
export PATH="$HOME/.local/bin:$PATH"
eval "$(zoxide init zsh)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/n0id/.lmstudio/bin"
# End of LM Studio CLI section

# Load custom aliases
[ -f ~/.zsh_aliases ] && source ~/.zsh_aliases

# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/n0id/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions

# Pocket 3 ingest shortcut
alias p3="python3 /Users/n0id/Dev/Scripts/pocket3ingest.py"