// Auto-generated by generate.py - do not edit
window.KEYBINDINGS_DATA = {
  "generated": "2026-02-04T21:53:04.885341",
  "sourceFiles": {
    "karabiner": "/Users/n0id/Dev/dotfiles/.config/karabiner/karabiner.json",
    "aerospace": "/Users/n0id/Dev/dotfiles/.config/aerospace/aerospace.toml",
    "hammerspoon": "/Users/n0id/Dev/dotfiles/hammerspoon",
    "rectangle": null,
    "raycast": null
  },
  "layers": {
    "hyper": {
      "name": "Hyper",
      "activatorKeys": [
        "caps"
      ],
      "layerClass": "",
      "description": "Caps Lock (hold) = \u2318\u2303\u2325\u21e7",
      "bindings": {
        "a": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Hyper A \u2192 ",
              "type": "system",
              "source": "karabiner",
              "desc": "Toggle tiling/floating",
              "raw_command": "/Users/n0id/.local/bin/aerospace-toggle-all-float",
              "icon": "sys",
              "iconData": null
            }
          ],
          "action": "Hyper A \u2192 ",
          "type": "system",
          "source": "karabiner",
          "desc": "Toggle tiling/floating",
          "raw_command": "/Users/n0id/.local/bin/aerospace-toggle-all-float",
          "condition": "hyper=1",
          "icon": "sys",
          "iconData": null
        },
        "g": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Mon",
              "type": "focus",
              "source": "karabiner",
              "desc": "Focus next monitor",
              "raw_command": "/opt/homebrew/bin/aerospace focus-monitor --wrap-around next",
              "icon": "focus",
              "iconData": "\u25b8"
            }
          ],
          "action": "Mon",
          "type": "focus",
          "source": "karabiner",
          "desc": "Focus next monitor",
          "raw_command": "/opt/homebrew/bin/aerospace focus-monitor --wrap-around next",
          "condition": "hyper=1",
          "icon": "focus",
          "iconData": "\u25b8"
        },
        "w": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Hyper W \u2192 ",
              "type": "system",
              "source": "karabiner",
              "desc": "Focus next monitor",
              "raw_command": "/Users/n0id/.local/bin/hyper-w-action",
              "icon": "sys",
              "iconData": null
            }
          ],
          "action": "Hyper W \u2192 ",
          "type": "system",
          "source": "karabiner",
          "desc": "Focus next monitor",
          "raw_command": "/Users/n0id/.local/bin/hyper-w-action",
          "condition": "hyper=1",
          "icon": "sys",
          "iconData": null
        },
        "r": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Hyper R \u2192 ",
              "type": "system",
              "source": "karabiner",
              "desc": "Move window to monitor + follow",
              "raw_command": "/Users/n0id/.local/bin/hyper-r-action",
              "icon": "sys",
              "iconData": null
            }
          ],
          "action": "Hyper R \u2192 ",
          "type": "system",
          "source": "karabiner",
          "desc": "Move window to monitor + follow",
          "raw_command": "/Users/n0id/.local/bin/hyper-r-action",
          "condition": "hyper=1",
          "icon": "sys",
          "iconData": null
        },
        "t": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Mon",
              "type": "focus",
              "source": "karabiner",
              "desc": "Focus next window",
              "raw_command": "/opt/homebrew/bin/aerospace move-node-to-monitor --wrap-around next && /opt/homebrew/bin/aerospace focus-monitor --wrap-around next",
              "icon": "focus",
              "iconData": "\u25b8"
            }
          ],
          "action": "Mon",
          "type": "focus",
          "source": "karabiner",
          "desc": "Focus next window",
          "raw_command": "/opt/homebrew/bin/aerospace move-node-to-monitor --wrap-around next && /opt/homebrew/bin/aerospace focus-monitor --wrap-around next",
          "condition": "hyper=1",
          "icon": "focus",
          "iconData": "\u25b8"
        },
        "s": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Hyper S \u2192 ",
              "type": "system",
              "source": "karabiner",
              "desc": "Left half (cycles)",
              "raw_command": "/Users/n0id/.local/bin/hyper-s-action",
              "icon": "sys",
              "iconData": null
            }
          ],
          "action": "Hyper S \u2192 ",
          "type": "system",
          "source": "karabiner",
          "desc": "Left half (cycles)",
          "raw_command": "/Users/n0id/.local/bin/hyper-s-action",
          "condition": "hyper=1",
          "icon": "sys",
          "iconData": null
        },
        "d": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Hyper D \u2192 ",
              "type": "system",
              "source": "karabiner",
              "desc": "Center",
              "raw_command": "/Users/n0id/.local/bin/hyper-d-action",
              "icon": "sys",
              "iconData": null
            }
          ],
          "action": "Hyper D \u2192 ",
          "type": "system",
          "source": "karabiner",
          "desc": "Center",
          "raw_command": "/Users/n0id/.local/bin/hyper-d-action",
          "condition": "hyper=1",
          "icon": "sys",
          "iconData": null
        },
        "f": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Hyper F \u2192 ",
              "type": "system",
              "source": "karabiner",
              "desc": "Right half (cycles)",
              "raw_command": "/Users/n0id/.local/bin/hyper-f-action",
              "icon": "sys",
              "iconData": null
            }
          ],
          "action": "Hyper F \u2192 ",
          "type": "system",
          "source": "karabiner",
          "desc": "Right half (cycles)",
          "raw_command": "/Users/n0id/.local/bin/hyper-f-action",
          "condition": "hyper=1",
          "icon": "sys",
          "iconData": null
        },
        "e": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Hyper E \u2192 ",
              "type": "system",
              "source": "karabiner",
              "desc": "Maximize",
              "raw_command": "/Users/n0id/.local/bin/hyper-e-action",
              "icon": "sys",
              "iconData": null
            }
          ],
          "action": "Hyper E \u2192 ",
          "type": "system",
          "source": "karabiner",
          "desc": "Maximize",
          "raw_command": "/Users/n0id/.local/bin/hyper-e-action",
          "condition": "hyper=1",
          "icon": "sys",
          "iconData": null
        },
        "x": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "1/3",
              "type": "position",
              "source": "karabiner",
              "desc": "First third",
              "raw_command": "open -g 'rectangle-pro://execute-action?name=first-third'",
              "icon": "pos",
              "iconData": "center"
            }
          ],
          "action": "1/3",
          "type": "position",
          "source": "karabiner",
          "desc": "First third",
          "raw_command": "open -g 'rectangle-pro://execute-action?name=first-third'",
          "condition": "hyper=1",
          "icon": "pos",
          "iconData": "center"
        },
        "c": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "C 1/3",
              "type": "position",
              "source": "karabiner",
              "desc": "Center third of screen",
              "raw_command": "open -g 'rectangle-pro://execute-action?name=center-third'",
              "icon": "pos",
              "iconData": "center"
            }
          ],
          "action": "C 1/3",
          "type": "position",
          "source": "karabiner",
          "desc": "Center third of screen",
          "raw_command": "open -g 'rectangle-pro://execute-action?name=center-third'",
          "condition": "hyper=1",
          "icon": "pos",
          "iconData": "center"
        },
        "v": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "3/3",
              "type": "position",
              "source": "karabiner",
              "desc": "Last third",
              "raw_command": "open -g 'rectangle-pro://execute-action?name=last-third'",
              "icon": "pos",
              "iconData": "center"
            }
          ],
          "action": "3/3",
          "type": "position",
          "source": "karabiner",
          "desc": "Last third",
          "raw_command": "open -g 'rectangle-pro://execute-action?name=last-third'",
          "condition": "hyper=1",
          "icon": "pos",
          "iconData": "center"
        },
        "z": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Cascade",
              "type": "position",
              "source": "karabiner",
              "desc": "Cascade all",
              "raw_command": "open -g 'rectangle-pro://execute-action?name=cascade-all'",
              "icon": "pos",
              "iconData": "center"
            }
          ],
          "action": "Cascade",
          "type": "position",
          "source": "karabiner",
          "desc": "Cascade all",
          "raw_command": "open -g 'rectangle-pro://execute-action?name=cascade-all'",
          "condition": "hyper=1",
          "icon": "pos",
          "iconData": "center"
        },
        "quote": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Bar",
              "type": "system",
              "source": "karabiner",
              "desc": "Toggle SketchyBar",
              "raw_command": "/opt/homebrew/bin/hs -c 'BarToggle:toggle()'",
              "icon": "sys",
              "iconData": null
            }
          ],
          "action": "Bar",
          "type": "system",
          "source": "karabiner",
          "desc": "Toggle SketchyBar",
          "raw_command": "/opt/homebrew/bin/hs -c 'BarToggle:toggle()'",
          "condition": "hyper=1",
          "icon": "sys",
          "iconData": null
        },
        "semicolon": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Svc",
              "type": "mode",
              "source": "karabiner",
              "desc": "Enter service mode",
              "raw_command": "/opt/homebrew/bin/aerospace mode service",
              "icon": "mode",
              "iconData": null
            }
          ],
          "action": "Svc",
          "type": "mode",
          "source": "karabiner",
          "desc": "Enter service mode",
          "raw_command": "/opt/homebrew/bin/aerospace mode service",
          "condition": "hyper=1",
          "icon": "mode",
          "iconData": null
        },
        "slash": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Hyper / \u2192 ",
              "type": "system",
              "source": "karabiner",
              "desc": "Hyper / \u2192 Sort windows by app into workspaces",
              "raw_command": "/Users/n0id/.local/bin/aerospace-sort-windows",
              "icon": "sys",
              "iconData": null
            }
          ],
          "action": "Hyper / \u2192 ",
          "type": "system",
          "source": "karabiner",
          "desc": "Hyper / \u2192 Sort windows by app into workspaces",
          "raw_command": "/Users/n0id/.local/bin/aerospace-sort-windows",
          "condition": "hyper=1",
          "icon": "sys",
          "iconData": null
        }
      }
    },
    "alt": {
      "name": "Alt",
      "activatorKeys": [
        "alt"
      ],
      "layerClass": "alt-layer",
      "description": "Option key bindings",
      "bindings": {
        "1": {
          "action": "workspace 1",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace 1",
          "raw_command": "workspace 1",
          "icon": "sys",
          "iconData": null
        },
        "b": {
          "action": "workspace B",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace B",
          "raw_command": "workspace B",
          "icon": "sys",
          "iconData": null
        },
        "c": {
          "action": "workspace C",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace C",
          "raw_command": "workspace C",
          "icon": "sys",
          "iconData": null
        },
        "d": {
          "action": "workspace D",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace D",
          "raw_command": "workspace D",
          "icon": "sys",
          "iconData": null
        },
        "f": {
          "action": "workspace F",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace F",
          "raw_command": "workspace F",
          "icon": "sys",
          "iconData": null
        },
        "g": {
          "action": "workspace G",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace G",
          "raw_command": "workspace G",
          "icon": "sys",
          "iconData": null
        },
        "i": {
          "action": "workspace I",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace I",
          "raw_command": "workspace I",
          "icon": "sys",
          "iconData": null
        },
        "k": {
          "action": "workspace K",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace K",
          "raw_command": "workspace K",
          "icon": "sys",
          "iconData": null
        },
        "l": {
          "action": "workspace L",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace L",
          "raw_command": "workspace L",
          "icon": "sys",
          "iconData": null
        },
        "r": {
          "action": "workspace R",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace R",
          "raw_command": "workspace R",
          "icon": "sys",
          "iconData": null
        },
        "s": {
          "action": "workspace S",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace S",
          "raw_command": "workspace S",
          "icon": "sys",
          "iconData": null
        },
        "v": {
          "action": "workspace V",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace V",
          "raw_command": "workspace V",
          "icon": "sys",
          "iconData": null
        },
        "w": {
          "action": "workspace W",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace W",
          "raw_command": "workspace W",
          "icon": "sys",
          "iconData": null
        }
      }
    },
    "alt-shift": {
      "name": "Alt+Shift",
      "activatorKeys": [
        "alt",
        "shift"
      ],
      "layerClass": "alt-layer",
      "description": "Option + Shift bindings",
      "bindings": {
        "1": {
          "action": "Go 1",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window + follow to workspace 1",
          "raw_command": "move-node-to-workspace 1 && workspace 1",
          "icon": "ws",
          "iconData": "1"
        },
        "b": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace B && workspace B",
          "icon": "ws",
          "iconData": ""
        },
        "c": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace C && workspace C",
          "icon": "ws",
          "iconData": ""
        },
        "d": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace D && workspace D",
          "icon": "ws",
          "iconData": ""
        },
        "f": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace F && workspace F",
          "icon": "ws",
          "iconData": ""
        },
        "g": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace G && workspace G",
          "icon": "ws",
          "iconData": ""
        },
        "i": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace I && workspace I",
          "icon": "ws",
          "iconData": ""
        },
        "k": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace K && workspace K",
          "icon": "ws",
          "iconData": ""
        },
        "l": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace L && workspace L",
          "icon": "ws",
          "iconData": ""
        },
        "r": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace R && workspace R",
          "icon": "ws",
          "iconData": ""
        },
        "s": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace S && workspace S",
          "icon": "ws",
          "iconData": ""
        },
        "v": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace V && workspace V",
          "icon": "ws",
          "iconData": ""
        },
        "w": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace W && workspace W",
          "icon": "ws",
          "iconData": ""
        }
      }
    },
    "service": {
      "name": "Service",
      "activatorKeys": [
        "caps",
        "semicolon"
      ],
      "layerClass": "service-layer",
      "description": "Hyper+; to enter",
      "bindings": {
        "esc": {
          "action": "Exit",
          "type": "mode",
          "source": "aerospace",
          "desc": "Exit",
          "raw_command": "mode main",
          "icon": "mode",
          "iconData": null
        },
        "r": {
          "action": "Reload",
          "type": "system",
          "source": "aerospace",
          "desc": "Reload config",
          "raw_command": "reload-config && mode main",
          "icon": "sys",
          "iconData": null
        },
        "q": {
          "action": "Close",
          "type": "system",
          "source": "aerospace",
          "desc": "Close all but current",
          "raw_command": "close-all-windows-but-current && mode main",
          "icon": "sys",
          "iconData": null
        },
        "d": {
          "action": "Toggle",
          "type": "mode",
          "source": "aerospace",
          "desc": "Enable/disable AeroSpace",
          "raw_command": "enable toggle && mode main",
          "icon": "mode",
          "iconData": null
        },
        "f": {
          "action": "Flatten",
          "type": "mode",
          "source": "aerospace",
          "desc": "Flatten workspace tree",
          "raw_command": "flatten-workspace-tree && mode main",
          "icon": "mode",
          "iconData": null
        }
      }
    }
  }
};
