// Auto-generated by generate.py - do not edit
window.KEYBINDINGS_DATA = {
  "generated": "2026-02-06T00:16:45.826337",
  "sourceFiles": {
    "karabiner": "/Users/n0id/Dev/dotfiles/.config/karabiner/karabiner.json",
    "aerospace": "/Users/n0id/Dev/dotfiles/.config/aerospace/aerospace.toml",
    "hammerspoon": "/Users/n0id/Dev/dotfiles/hammerspoon",
    "rectangle": null,
    "raycast": null
  },
  "layers": {
    "hyper": {
      "name": "Hyper",
      "activatorKeys": [
        "caps"
      ],
      "layerClass": "",
      "description": "Caps Lock (hold) = \u2318\u2303\u2325\u21e7",
      "bindings": {
        "a": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Hyper A \u2192 ",
              "type": "system",
              "source": "karabiner",
              "desc": "Toggle tiling/floating",
              "raw_command": "/Users/n0id/.local/bin/aerospace-toggle-all-float",
              "icon": "sys",
              "iconData": null
            }
          ],
          "action": "Hyper A \u2192 ",
          "type": "system",
          "source": "karabiner",
          "desc": "Toggle tiling/floating",
          "raw_command": "/Users/n0id/.local/bin/aerospace-toggle-all-float",
          "condition": "hyper=1",
          "icon": "sys",
          "iconData": null
        },
        "t": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Mon",
              "type": "focus",
              "source": "karabiner",
              "desc": "Focus next window",
              "raw_command": "/opt/homebrew/bin/aerospace focus-monitor --wrap-around next",
              "icon": "focus",
              "iconData": "\u25b8"
            }
          ],
          "action": "Mon",
          "type": "focus",
          "source": "karabiner",
          "desc": "Focus next window",
          "raw_command": "/opt/homebrew/bin/aerospace focus-monitor --wrap-around next",
          "condition": "hyper=1",
          "icon": "focus",
          "iconData": "\u25b8"
        },
        "s": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Foc L",
              "type": "focus",
              "source": "karabiner",
              "desc": "Left half (cycles)",
              "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=first-third'; else /opt/homebrew/bin/aerospace move left; fi",
              "icon": "focus",
              "iconData": "\u25c2"
            }
          ],
          "action": "Foc L",
          "type": "focus",
          "source": "karabiner",
          "desc": "Left half (cycles)",
          "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=first-third'; else /opt/homebrew/bin/aerospace move left; fi",
          "condition": "hyper=1",
          "icon": "focus",
          "iconData": "\u25c2"
        },
        "f": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Foc R",
              "type": "focus",
              "source": "karabiner",
              "desc": "Right half (cycles)",
              "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=last-third'; else /opt/homebrew/bin/aerospace move right; fi",
              "icon": "focus",
              "iconData": "\u25b8"
            }
          ],
          "action": "Foc R",
          "type": "focus",
          "source": "karabiner",
          "desc": "Right half (cycles)",
          "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=last-third'; else /opt/homebrew/bin/aerospace move right; fi",
          "condition": "hyper=1",
          "icon": "focus",
          "iconData": "\u25b8"
        },
        "g": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Mon",
              "type": "focus",
              "source": "karabiner",
              "desc": "Focus next monitor",
              "raw_command": "/opt/homebrew/bin/aerospace move-node-to-monitor --wrap-around next && /opt/homebrew/bin/aerospace focus-monitor --wrap-around next",
              "icon": "focus",
              "iconData": "\u25b8"
            }
          ],
          "action": "Mon",
          "type": "focus",
          "source": "karabiner",
          "desc": "Focus next monitor",
          "raw_command": "/opt/homebrew/bin/aerospace move-node-to-monitor --wrap-around next && /opt/homebrew/bin/aerospace focus-monitor --wrap-around next",
          "condition": "hyper=1",
          "icon": "focus",
          "iconData": "\u25b8"
        },
        "w": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Prev",
              "type": "focus",
              "source": "karabiner",
              "desc": "Focus next monitor",
              "raw_command": "/Users/n0id/.local/bin/aerospace-focus-wrap-prev",
              "icon": "focus",
              "iconData": "\u25c2"
            }
          ],
          "action": "Prev",
          "type": "focus",
          "source": "karabiner",
          "desc": "Focus next monitor",
          "raw_command": "/Users/n0id/.local/bin/aerospace-focus-wrap-prev",
          "condition": "hyper=1",
          "icon": "focus",
          "iconData": "\u25c2"
        },
        "e": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Foc U",
              "type": "focus",
              "source": "karabiner",
              "desc": "Maximize",
              "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=maximize'; else /opt/homebrew/bin/aerospace move up; fi",
              "icon": "focus",
              "iconData": "\u25b4"
            }
          ],
          "action": "Foc U",
          "type": "focus",
          "source": "karabiner",
          "desc": "Maximize",
          "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=maximize'; else /opt/homebrew/bin/aerospace move up; fi",
          "condition": "hyper=1",
          "icon": "focus",
          "iconData": "\u25b4"
        },
        "r": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Next",
              "type": "focus",
              "source": "karabiner",
              "desc": "Move window to monitor + follow",
              "raw_command": "/Users/n0id/.local/bin/aerospace-focus-wrap-next",
              "icon": "focus",
              "iconData": "\u25b8"
            }
          ],
          "action": "Next",
          "type": "focus",
          "source": "karabiner",
          "desc": "Move window to monitor + follow",
          "raw_command": "/Users/n0id/.local/bin/aerospace-focus-wrap-next",
          "condition": "hyper=1",
          "icon": "focus",
          "iconData": "\u25b8"
        },
        "d": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Foc D",
              "type": "focus",
              "source": "karabiner",
              "desc": "Center",
              "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=center-third'; else /opt/homebrew/bin/aerospace move down; fi",
              "icon": "focus",
              "iconData": "\u25be"
            }
          ],
          "action": "Foc D",
          "type": "focus",
          "source": "karabiner",
          "desc": "Center",
          "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=center-third'; else /opt/homebrew/bin/aerospace move down; fi",
          "condition": "hyper=1",
          "icon": "focus",
          "iconData": "\u25be"
        },
        "c": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Flat",
              "type": "mode",
              "source": "karabiner",
              "desc": "Flatten workspace tree",
              "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=center-two-thirds'; else /opt/homebrew/bin/aerospace flatten-workspace-tree && /opt/homebrew/bin/aerospace layout tiles horizontal; fi",
              "icon": "mode",
              "iconData": null
            }
          ],
          "action": "Flat",
          "type": "mode",
          "source": "karabiner",
          "desc": "Flatten workspace tree",
          "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=center-two-thirds'; else /opt/homebrew/bin/aerospace flatten-workspace-tree && /opt/homebrew/bin/aerospace layout tiles horizontal; fi",
          "condition": "hyper=1",
          "icon": "mode",
          "iconData": null
        },
        "x": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "-150",
              "type": "resize",
              "source": "karabiner",
              "desc": "First third",
              "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=first-two-thirds'; else /opt/homebrew/bin/aerospace resize smart -150; fi",
              "icon": "resize",
              "iconData": "shrink"
            }
          ],
          "action": "-150",
          "type": "resize",
          "source": "karabiner",
          "desc": "First third",
          "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=first-two-thirds'; else /opt/homebrew/bin/aerospace resize smart -150; fi",
          "condition": "hyper=1",
          "icon": "resize",
          "iconData": "shrink"
        },
        "v": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "+150",
              "type": "resize",
              "source": "karabiner",
              "desc": "Last third",
              "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=last-two-thirds'; else /opt/homebrew/bin/aerospace resize smart +150; fi",
              "icon": "resize",
              "iconData": "grow"
            }
          ],
          "action": "+150",
          "type": "resize",
          "source": "karabiner",
          "desc": "Last third",
          "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then open -g 'rectangle://execute-action?name=last-two-thirds'; else /opt/homebrew/bin/aerospace resize smart +150; fi",
          "condition": "hyper=1",
          "icon": "resize",
          "iconData": "grow"
        },
        "q": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Rect",
              "type": "position",
              "source": "karabiner",
              "desc": "Focus prev window",
              "raw_command": "[ \"$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}')\" = floating ] && open -g 'rectangle://execute-action?name=cascade-all'",
              "icon": "pos",
              "iconData": "center"
            }
          ],
          "action": "Rect",
          "type": "position",
          "source": "karabiner",
          "desc": "Focus prev window",
          "raw_command": "[ \"$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}')\" = floating ] && open -g 'rectangle://execute-action?name=cascade-all'",
          "condition": "hyper=1",
          "icon": "pos",
          "iconData": "center"
        },
        "z": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Float",
              "type": "mode",
              "source": "karabiner",
              "desc": "Cascade all",
              "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then /opt/homebrew/bin/aerospace layout tiling; else /opt/homebrew/bin/aerospace layout floating; fi",
              "icon": "mode",
              "iconData": null
            }
          ],
          "action": "Float",
          "type": "mode",
          "source": "karabiner",
          "desc": "Cascade all",
          "raw_command": "L=$(/opt/homebrew/bin/aerospace list-windows --focused --format '%{window-layout}'); if [ \"$L\" = floating ]; then /opt/homebrew/bin/aerospace layout tiling; else /opt/homebrew/bin/aerospace layout floating; fi",
          "condition": "hyper=1",
          "icon": "mode",
          "iconData": null
        },
        "b": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Hyper B \u2192 ",
              "type": "system",
              "source": "karabiner",
              "desc": "Hyper B \u2192 Swap monitor workspaces",
              "raw_command": "/Users/n0id/.local/bin/aerospace-swap-workspaces.sh",
              "icon": "sys",
              "iconData": null
            }
          ],
          "action": "Hyper B \u2192 ",
          "type": "system",
          "source": "karabiner",
          "desc": "Hyper B \u2192 Swap monitor workspaces",
          "raw_command": "/Users/n0id/.local/bin/aerospace-swap-workspaces.sh",
          "condition": "hyper=1",
          "icon": "sys",
          "iconData": null
        },
        "quote": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Bar",
              "type": "system",
              "source": "karabiner",
              "desc": "Toggle SketchyBar",
              "raw_command": "/opt/homebrew/bin/hs -c 'BarToggle:toggle()'",
              "icon": "sys",
              "iconData": null
            }
          ],
          "action": "Bar",
          "type": "system",
          "source": "karabiner",
          "desc": "Toggle SketchyBar",
          "raw_command": "/opt/homebrew/bin/hs -c 'BarToggle:toggle()'",
          "condition": "hyper=1",
          "icon": "sys",
          "iconData": null
        },
        "semicolon": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Svc",
              "type": "mode",
              "source": "karabiner",
              "desc": "Enter service mode",
              "raw_command": "/opt/homebrew/bin/aerospace mode service",
              "icon": "mode",
              "iconData": null
            }
          ],
          "action": "Svc",
          "type": "mode",
          "source": "karabiner",
          "desc": "Enter service mode",
          "raw_command": "/opt/homebrew/bin/aerospace mode service",
          "condition": "hyper=1",
          "icon": "mode",
          "iconData": null
        },
        "slash": {
          "variants": [
            {
              "condition": "hyper=1",
              "action": "Hyper / \u2192 ",
              "type": "system",
              "source": "karabiner",
              "desc": "Hyper / \u2192 Sort windows by app into workspaces",
              "raw_command": "/Users/n0id/.local/bin/aerospace-sort-windows",
              "icon": "sys",
              "iconData": null
            }
          ],
          "action": "Hyper / \u2192 ",
          "type": "system",
          "source": "karabiner",
          "desc": "Hyper / \u2192 Sort windows by app into workspaces",
          "raw_command": "/Users/n0id/.local/bin/aerospace-sort-windows",
          "condition": "hyper=1",
          "icon": "sys",
          "iconData": null
        }
      }
    },
    "alt": {
      "name": "Alt",
      "activatorKeys": [
        "alt"
      ],
      "layerClass": "alt-layer",
      "description": "Option key bindings",
      "bindings": {
        "b": {
          "action": "workspace B",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace B",
          "raw_command": "workspace B",
          "icon": "sys",
          "iconData": null
        },
        "c": {
          "action": "workspace C",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace C",
          "raw_command": "workspace C",
          "icon": "sys",
          "iconData": null
        },
        "d": {
          "action": "workspace D",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace D",
          "raw_command": "workspace D",
          "icon": "sys",
          "iconData": null
        },
        "f": {
          "action": "workspace F",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace F",
          "raw_command": "workspace F",
          "icon": "sys",
          "iconData": null
        },
        "g": {
          "action": "workspace G",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace G",
          "raw_command": "workspace G",
          "icon": "sys",
          "iconData": null
        },
        "i": {
          "action": "workspace I",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace I",
          "raw_command": "workspace I",
          "icon": "sys",
          "iconData": null
        },
        "k": {
          "action": "workspace K",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace K",
          "raw_command": "workspace K",
          "icon": "sys",
          "iconData": null
        },
        "l": {
          "action": "workspace L",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace L",
          "raw_command": "workspace L",
          "icon": "sys",
          "iconData": null
        },
        "r": {
          "action": "workspace R",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace R",
          "raw_command": "workspace R",
          "icon": "sys",
          "iconData": null
        },
        "s": {
          "action": "workspace S",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace S",
          "raw_command": "workspace S",
          "icon": "sys",
          "iconData": null
        },
        "v": {
          "action": "workspace V",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace V",
          "raw_command": "workspace V",
          "icon": "sys",
          "iconData": null
        },
        "w": {
          "action": "workspace W",
          "type": "system",
          "source": "aerospace",
          "desc": "workspace W",
          "raw_command": "workspace W",
          "icon": "sys",
          "iconData": null
        }
      }
    },
    "alt-shift": {
      "name": "Alt+Shift",
      "activatorKeys": [
        "alt",
        "shift"
      ],
      "layerClass": "alt-layer",
      "description": "Option + Shift bindings",
      "bindings": {
        "b": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace B && workspace B",
          "icon": "ws",
          "iconData": ""
        },
        "c": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace C && workspace C",
          "icon": "ws",
          "iconData": ""
        },
        "d": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace D && workspace D",
          "icon": "ws",
          "iconData": ""
        },
        "f": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace F && workspace F",
          "icon": "ws",
          "iconData": ""
        },
        "g": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace G && workspace G",
          "icon": "ws",
          "iconData": ""
        },
        "i": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace I && workspace I",
          "icon": "ws",
          "iconData": ""
        },
        "k": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace K && workspace K",
          "icon": "ws",
          "iconData": ""
        },
        "l": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace L && workspace L",
          "icon": "ws",
          "iconData": ""
        },
        "r": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace R && workspace R",
          "icon": "ws",
          "iconData": ""
        },
        "s": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace S && workspace S",
          "icon": "ws",
          "iconData": ""
        },
        "v": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace V && workspace V",
          "icon": "ws",
          "iconData": ""
        },
        "w": {
          "action": "Send ?",
          "type": "workspace",
          "source": "aerospace",
          "desc": "Send window to workspace ? (stay)",
          "raw_command": "move-node-to-workspace W && workspace W",
          "icon": "ws",
          "iconData": ""
        }
      }
    },
    "service": {
      "name": "Service",
      "activatorKeys": [
        "caps",
        "semicolon"
      ],
      "layerClass": "service-layer",
      "description": "Hyper+; to enter",
      "bindings": {
        "esc": {
          "action": "Exit",
          "type": "mode",
          "source": "aerospace",
          "desc": "Exit",
          "raw_command": "mode main",
          "icon": "mode",
          "iconData": null
        },
        "r": {
          "action": "Reload",
          "type": "system",
          "source": "aerospace",
          "desc": "Reload config",
          "raw_command": "reload-config && mode main",
          "icon": "sys",
          "iconData": null
        },
        "q": {
          "action": "Close",
          "type": "system",
          "source": "aerospace",
          "desc": "Close all but current",
          "raw_command": "close-all-windows-but-current && mode main",
          "icon": "sys",
          "iconData": null
        },
        "d": {
          "action": "Toggle",
          "type": "mode",
          "source": "aerospace",
          "desc": "Enable/disable AeroSpace",
          "raw_command": "enable toggle && mode main",
          "icon": "mode",
          "iconData": null
        },
        "f": {
          "action": "Flatten",
          "type": "mode",
          "source": "aerospace",
          "desc": "Flatten workspace tree",
          "raw_command": "flatten-workspace-tree && mode main",
          "icon": "mode",
          "iconData": null
        }
      }
    }
  }
};
